WebJogos/WebJogos/Models/Enum.cs
using System.ComponentModel.DataAnnotations;

namespace WebJogos.Models
{
    public enum Status
    {
        [Display(Name = "Completo")]
        Completo,

        [Display(Name = "Parcial")]
        Parcial,

        [Display(Name = "Não iniciado")]
        NaoIniciado
    }
}

WebJogos/WebJogos/Models/ErrorViewModel.cs
namespace WebJogos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebJogos/WebJogos/Models/TaskItem.cs
using System.Net.NetworkInformation;

namespace WebJogos.Models
{
    public class TaskItem
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public int Pontuacao { get; set; }

        public int Nota { get; set; }
        public DateTime DataCriacao { get; set; } = DateTime.Now;
        public Status Status { get; set; }
        public decimal? Valor { get; set; } 


    }
}

WebJogos/WebJogos/Controllers/DesejosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebJogos.Models;

namespace WebJogos.Controllers
{
    public class DesejosController : Controller
    {
        public static List<TaskItem> listaDesejos = new List<TaskItem>();
        public static int proximoId = 1;

        public IActionResult Index()
        {
            return View("Listar", listaDesejos);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(TaskItem task)
        {
            if (task.Id == 0)
            {
                task.Id = proximoId++;
                listaDesejos.Add(task);
            }
            else
            {
                TaskItem existingTask = listaDesejos.FirstOrDefault(t => t.Id == task.Id);

                if (existingTask != null)
                {
                    existingTask.Titulo = task.Titulo;
                    existingTask.Descricao = task.Descricao;
                    existingTask.Valor = task.Valor;
                }
            }

            return RedirectToAction("Index");
        }

        public IActionResult Listar()
        {
            return View(listaDesejos);
        }

        public IActionResult Excluir(int id)
        {
            try
            {
                var tarefa = listaDesejos.FirstOrDefault(t => t.Id == id);
                if (tarefa != null)
                {
                    listaDesejos.Remove(tarefa);
                }
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, error = ex.Message });
            }
        }

        [HttpGet]
        public IActionResult ObterTarefa(int id)
        {
            var tarefa = listaDesejos.FirstOrDefault(t => t.Id == id);
            if (tarefa != null)
            {
                return View("Cadastrar", tarefa);
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult PesquisarJogo(string termo)
        {

            var tarefasEncontradas = listaDesejos.Where(t => t.Titulo.Contains(termo) || t.Descricao.Contains(termo)).ToList();

            return View("Listar", tarefasEncontradas);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebJogos/WebJogos/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebJogos.Models;

namespace WebJogos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private static List<TaskItem> listaJogos = new List<TaskItem>();
        private static int proximoId = 1;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(TaskItem task)
        {
            if (task.Id == 0)
            {
                task.Id = proximoId++;
                listaJogos.Add(task);
            }
            else
            {
                TaskItem existingTask = listaJogos.FirstOrDefault(t => t.Id == task.Id);

                if (existingTask != null)
                {
                    existingTask.Status = task.Status;
                    existingTask.Titulo = task.Titulo;
                    existingTask.Descricao = task.Descricao;
                    existingTask.Pontuacao = task.Pontuacao;
                }

            }

            return RedirectToAction("Listar");
        }

        public IActionResult Listar()
        {
            return View(listaJogos);
        }

        public IActionResult Excluir(int id)
        {
            try
            {
                var tarefa = listaJogos.FirstOrDefault(t => t.Id == id);
                if (tarefa != null)
                {
                    listaJogos.Remove(tarefa);
                }
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, error = ex.Message });
            }
        }

        [HttpGet]
        public IActionResult ObterTarefa(int id)
        {
            var tarefa = listaJogos.FirstOrDefault(t => t.Id == id);
            if (tarefa != null)
            {
                return View("Cadastrar", tarefa);
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult PesquisarJogo(string termo)
        {

            var resultadoBiblioteca = listaJogos.Where(t => t.Titulo.Contains(termo) || t.Descricao.Contains(termo)).ToList();

            return View("Listar", resultadoBiblioteca);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebJogos/WebJogos/Views/Desejos/Cadastrar.cshtml
@model TaskItem

<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 cadastrar-card">
            <form asp-controller="Desejos" asp-action="Create">
                <fieldset>
                    <h2 class="text-center mt-3">Adicionar à Lista de Desejos</h2>

                    <input asp-for="Id" type="hidden" />

                    <div class="form-group">
                        <label class="col-form-label mt-4" for="inputTitulo">Título</label>
                        <input asp-for="Titulo" type="text" class="form-control" placeholder="Nome do Jogo" id="inputTitulo">
                    </div>

                    <div class="form-group">
                        <label for="inputDescricao" class="form-label mt-4">Descrição</label>
                        <textarea asp-for="Descricao" class="form-control" id="inputDescricao" rows="3"></textarea>
                    </div>
                    <div class="form-group mt-3">
                        <label for="Valor">Valor atual do jogo</label>
                        <input asp-for="Valor" class="form-control" type="number" step="0.01" min="0" placeholder="00.00" />
                        <span asp-validation-for="Valor" class="text-danger"></span>
                    </div>

                    <label for="customRange3" class="form-label mt-4">Nota do Jogo - Reviews </label>
                    <div class=" d-flex justify-content-between">
                        @for (int i = 0; i <= 10; i++)
                        {
                            <span> @i </span>
                        }
                    </div>
                    <input asp-for="Pontuacao" type="range" class="form-range" min="0" max="10" step="0.0" id="customRange3">
                    <div class="d-flex justify-content-between mt-3">

                    <div class="d-flex justify-content-end gap-2 mt-3">
                        <a asp-action="Index" asp-controller="Desejos" class="btn btn-dark">Cancelar</a>
                        <input type="submit" class="btn btn-danger" value="Salvar" />
                    </div>

                </fieldset>
            </form>
        </div>
    </div>
</div>

WebJogos/WebJogos/Views/Desejos/Listar.cshtml
@model List<TaskItem>

<div class="container">
    <div class="row justify-content-center mt-5">
        <h2 class="text-center text-primary">Lista de Desejos</h2>
        <div class="row mt-3">
            @if (Model.Any())
            {
                @foreach (var task in Model)
                {
                    <div class="col-md-4 mb-3">
                        <div class="card border-primary" style="max-width: 20rem;">
                            <div class="card-header d-flex justify-content-between">
                                Lista de Desejos
                                <p>@task.DataCriacao.ToString("dd/MM/yyyy")</p>
                            </div>
                            <div class="card-body">
                                <h4 class="card-title">@task.Titulo</h4>
                                <p class="card-text">@task.Descricao</p>
                                <p class="card-text">R$ @task.Valor</p>
                                <div class="card-action d-flex justify-content-between">
                                    <span class="badge bg-info">@task.Pontuacao pontos</span>
                                    <div class="justify-content-around">
                                        <a asp-action="ObterTarefa" asp-route-id="@task.Id" class="btn btn-warning btn-sm" data-task-id="@task.Id">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                                            </svg>
                                        </a>
                                        <a asp-action="Excluir" asp-route-id="@task.Id" class="btn btn-warning btn-sm excluir-tarefa" data-task-id="@task.Id" data-toggle="modal" data-target="#confirmacaoModal">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z" />
                                                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z" />
                                            </svg>
                                        </a>
                                        <div class="modal" id="confirmacaoModal">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title">Apagar jogo</h5>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Tem certeza que deseja excluir este jogo?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-primary" id="confirmarExclusao">Confirmar</button>
                                                        <button type="button" class="btn btn-secondary" id="cancelarExclusao" data-bs-dismiss="modal">Cancelar</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            }
            else
            {
                <p class="text-center">Sua lista de desejos está vazia.</p>
            }
        </div>
    <div class="d-flex justify-content-center mt-4">
            <a asp-controller="Desejos" asp-action="Cadastrar" class="btn btn-primary btn-lg">
            <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" class="bi bi-plus" viewBox="0 0 16 16">
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
            </svg>
            Adicionar jogo 
        </a>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            var taskId = null;

            $('.excluir-tarefa').click(function () {
                taskId = $(this).data('task-id');
            });

            $('#confirmarExclusao').click(function () {
                if (!taskId) return;

                $.post('/Desejos/Excluir', { id: taskId }, function (result) {
                    if (result.success) {
                        window.location.reload();
                    } else {
                        alert("Erro ao excluir.");
                    }
                });
            });

                $("#cancelarExclusao").click(function () {
                window.location.reload();
            });
        });
    </script>
}

WebJogos/WebJogos/Views/Home/Cadastrar.cshtml
@model TaskItem

<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 cadastrar-card ">
            <form asp-controller="Home" asp-action="Create">
                <fieldset>
                    <h2 class="text-center mt-3">Cadastrar Jogo</h2>
                    <input asp-for="Id" type="hidden" />
                    <div class="form-group">
                        <label asp-for="Status">Status do Jogo</label>
                        <select asp-for="Status" asp-items="Html.GetEnumSelectList<Status>()" class="form-control"></select>
                    </div>
                    <div class="form-group">
                        <label class="col-form-label mt-4" for="inputDefault">Título</label>
                        <input asp-for="Titulo" type="text" class="form-control" placeholder="Nome do Jogo" id="inputDefault">
                    </div>
                    <div class="form-group">
                        <label for="exampleTextarea" class="form-label mt-4">Descrição</label>
                        <textarea asp-for="Descricao" class="form-control" id="exampleTextarea" rows="3"></textarea>
                    </div>
                    <label for="customRange3" class="form-label mt-4">Nota do Jogo</label>
                    <div class=" d-flex justify-content-between"> @for (int i = 0; i <=10; i++)
                        {
                            <span> @i </span>
                        }
                    </div>
                        <input asp-for="Pontuacao" type="range" class="form-range" min="0" max="10" step="0.0" id="customRange3">
                    <div class="d-flex justify-content-end gap-2 mt-3">
                        <a asp-action="Index" asp-controller="Home" class="btn btn-dark">Cancelar</a>
                        <input type="submit" class="btn btn-danger" value="Salvar" />
                    </div>

                </fieldset>
            </form>
        </div>
    </div>
</div>

WebJogos/WebJogos/Views/Home/EditarTarefa.cshtml
@model TaskItem

<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <form asp-controller="Home" asp-action="Editar">
                <fieldset>
                    <legend class="text-center mt-3">Cadastrar tarefa</legend>
                    <div class="form-group">
                        <label class="col-form-label mt-4" for="inputDefault">Título</label>
                        <input asp-for="Titulo" type="text" class="form-control" placeholder="Nome do Jogo" id="inputDefault">
                    </div>
                    <div class="form-group">
                        <label for="exampleTextarea" class="form-label mt-4">Descrição</label>
                        <textarea asp-for="Descricao" class="form-control" id="exampleTextarea" rows="3"></textarea>
                    </div>
                    <label for="customRange3" class="form-label">Pontuação</label>
                    <input asp-for="Pontuacao" type="range" class="form-range" min="1" max="100" step="0.0" id="customRange3">
                    <div class="d-flex justify-content-between mt-3">
                        <input type="submit" asp-controller="Home" asp-action="Index" class="btn btn-outline-light" value="Cancelar" />
                        <input type="submit" class="btn btn-danger" value="Salvar" />
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>

WebJogos/WebJogos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="container mt-5">
    <div class="text-center">
        <h1 class="display-4 text-primary mb-4">GESTÃO DE JOGOS</h1>
        <h5 class="mb-5">O que deseja fazer hoje?</h5>

        <div class="row justify-content-center mb-4">
            <div class="col-md-4 mb-3">
                <a asp-controller="Home" asp-action="Listar" class="btn btn-outline-primary btn-lg w-100 py-3">
                    Ver sua biblioteca de jogos
                </a>
            </div>
            <div class="col-md-4 mb-3">
                <a asp-controller="Desejos" asp-action="Index" class="btn btn-outline-primary btn-lg w-100 py-3">
                    Ver sua lista de desejos
                </a>
            </div>
        </div>
        <p class="mt-5"> <a href="https://github.com/PedroHGGomes?tab=repositories">GitHub - Pedro Gomes</a></p>
    </div>
</div>

WebJogos/WebJogos/Views/Home/Listar.cshtml
@model List<TaskItem>

<div class="container">
    <div class="row justify-content-center mt-5">
        <h2 class="text-center text-success">Lista de Tarefas</h2>
        <div class="row mt-3">
            @if (Model.Any())
            {
                @foreach (var task in Model)
                {
                    <div class="col-md-4 mb-3">
                        <div class="card border-success" style="max-width: 20rem;">
                            <div class="card-header d-flex justify-content-between">
                                Tarefa @task.Status
                                <p>@task.DataCriacao.ToString("dd/MM/yyyy")</p>
                            </div>
                            <div class="card-body">
                                <h4 class="card-title">@task.Titulo</h4>
                                <p class="card-text">@task.Descricao</p>
                                <div class="card-action d-flex justify-content-between">
                                    <span class="badge bg-info">@task.Pontuacao pontos</span>
                                    <div class="justify-content-around">
                                        <a asp-action="ObterTarefa" asp-route-id="@task.Id" class="btn btn-warning btn-sm" data-task-id="@task.Id">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                                            </svg>
                                        </a>
                                        <a asp-action="Excluir" asp-route-id="@task.Id" class="btn btn-warning btn-sm excluir-tarefa" data-task-id="@task.Id" data-toggle="modal" data-target="#confirmacaoModal">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z" />
                                                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z" />
                                            </svg>
                                        </a>
                                        <div class="modal" id="confirmacaoModal">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title">Apagar tarefa</h5>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Tem certeza que deseja excluir esta tarefa?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-primary" id="confirmarExclusao">Confirmar</button>
                                                        <button type="button" class="btn btn-secondary" id="cancelarExclusao" data-bs-dismiss="modal">Cancelar</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            }
            else
            {
                <p class="text-center">Você não tem nenhuma tarefa cadastrada.</p>
            }

        </div>

    </div>
    <div class="d-flex justify-content-center mt-4">
        <a asp-controller="Home" asp-action="Cadastrar" class="btn btn-primary btn-lg">
            <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
            </svg>
            Nova tarefa
        </a>
    </div>
</div>
<script>

    $(document).ready(function () {

        var taskId = null;

        $('.excluir-tarefa').click(function () {
            taskId = $(this).data('task-id');
        });

        $('#confirmarExclusao').click(function () {
            if (taskId === null) {
                console.log('ID do jogo não definido.');
                return;
            }

            $.post('/Home/Excluir', { id: taskId }, function (result) {
                if (result.success) {
                    window.location.reload();
                } else {
                    alert("Erro ao excluir jogo.");
                }
            });

        });

        $("#cancelarExclusao").click(function () {
            window.location.reload();
        });

    });
</script>

WebJogos/WebJogos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebJogos </title>
    <link rel="stylesheet" href="https://bootswatch.com/5/solar/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <a class="navbar-brand" href="/Home">WebJogos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="/Home">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Biblioteca</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="/Home/Cadastrar">Adicionar</a>
                                <a class="dropdown-item" href="/Home/Listar">Listar</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Lista de Desejos</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="/Desejos/Cadastrar">Adicionar</a>
                                <a class="dropdown-item" href="/Desejos/Index">Listar</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Home/Privacy">Privacidade</a>
                        </li>
                    </ul>
                    <form class="d-flex" id="searchForm" asp-controller="Home" asp-action="PesquisarJogo">
                        <input class="form-control me-sm-2" type="search" placeholder="Search" id="searchInput">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>
    $(document).ready(function () {
        $('#searchForm').submit(function (e) {
            var termo = $('#searchInput').val();
            if (termo) {

                window.location.href = '/Home/PesquisarJogo?termo=' + termo;
            }
            e.preventDefault();
        });
    });

</script>